name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]

# 设置token访问权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.8.1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install dependencies
        run: pnpm install

      - name: Build with VitePress
        run: | 
          pnpm run docs:build
          touch .nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy  # 修正：移除冒号后的空格
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
