name: Deploy VitePress site to Pages

on:
  push:
    branches: [master]

env:
  PNPM_VERSION: 8.19.0
  NODE_VERSION: 18

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # 更新到最新版
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          PNPM_CACHE_FOLDER: .pnpm-store

      - name: Build with VitePress
        run: | 
          pnpm run docs:build
          touch .vitepress/dist/.nojekyll  # 修正路径

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # 更新到v3
        with:
          path: .vitepress/dist

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3  # 更新到v3
